use std::{borrow::Cow, fmt, str::FromStr};

use super::Span;

#[derive(Debug, Clone, PartialEq)]
pub struct Book<'a> {
    pub code: BookCode,
    pub description: Cow<'a, str>,
    /// Source range of the whole `\id` line.
    pub span: Span,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BookCategory {
    OldTestament,
    NewTestament,
    Deuterocanon,
    NonScripture,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BookCode {
    // Old Testament
    Gen,
    Exo,
    Lev,
    Num,
    Deu,
    Jos,
    Jdg,
    Rut,
    Sa1,
    Sa2,
    Ki1,
    Ki2,
    Ch1,
    Ch2,
    Ezr,
    Neh,
    Est,
    Job,
    Psa,
    Pro,
    Ecc,
    Sng,
    Isa,
    Jer,
    Lam,
    Ezk,
    Dan,
    Hos,
    Jol,
    Amo,
    Oba,
    Jon,
    Mic,
    Nam,
    Hab,
    Zep,
    Hag,
    Zec,
    Mal,
    // New Testament
    Mat,
    Mrk,
    Luk,
    Jhn,
    Act,
    Rom,
    Co1,
    Co2,
    Gal,
    Eph,
    Php,
    Col,
    Th1,
    Th2,
    Ti1,
    Ti2,
    Tit,
    Phm,
    Heb,
    Jas,
    Pe1,
    Pe2,
    Jn1,
    Jn2,
    Jn3,
    Jud,
    Rev,
    // Deuterocanon
    Tob,
    Jdt,
    Esg,
    Wis,
    Sir,
    Bar,
    Lje,
    S3y,
    Sus,
    Bel,
    Ma1,
    Ma2,
    Ma3,
    Ma4,
    Es1,
    Es2,
    Man,
    Ps2,
    Oda,
    Pss,
    Eza,
    Ez5,
    Ez6,
    Dag,
    Ps3,
    Ba2,
    Lba,
    Jub,
    Eno,
    Mq1,
    Mq2,
    Mq3,
    Rep,
    Ba4,
    Lao,
    // Non scripture
    Xxa,
    Xxb,
    Xxc,
    Xxd,
    Xxe,
    Xxf,
    Xxg,
    Frt,
    Bak,
    Oth,
    Int,
    Cnc,
    Glo,
    Tdx,
    Ndx,
}

use BookCode::*;

impl BookCode {
    pub fn category(&self) -> BookCategory {
        match self {
            Gen | Exo | Lev | Num | Deu | Jos | Jdg | Rut | Sa1 | Sa2 | Ki1 | Ki2 | Ch1 | Ch2
            | Ezr | Neh | Est | Job | Psa | Pro | Ecc | Sng | Isa | Jer | Lam | Ezk | Dan | Hos
            | Jol | Amo | Oba | Jon | Mic | Nam | Hab | Zep | Hag | Zec | Mal => {
                BookCategory::OldTestament
            }
            Mat | Mrk | Luk | Jhn | Act | Rom | Co1 | Co2 | Gal | Eph | Php | Col | Th1 | Th2
            | Ti1 | Ti2 | Tit | Phm | Heb | Jas | Pe1 | Pe2 | Jn1 | Jn2 | Jn3 | Jud | Rev => {
                BookCategory::NewTestament
            }
            Tob | Jdt | Esg | Wis | Sir | Bar | Lje | S3y | Sus | Bel | Ma1 | Ma2 | Ma3 | Ma4
            | Es1 | Es2 | Man | Ps2 | Oda | Pss | Eza | Ez5 | Ez6 | Dag | Ps3 | Ba2 | Lba | Jub
            | Eno | Mq1 | Mq2 | Mq3 | Rep | Ba4 | Lao => BookCategory::Deuterocanon,
            Xxa | Xxb | Xxc | Xxd | Xxe | Xxf | Xxg | Frt | Bak | Oth | Int | Cnc | Glo | Tdx
            | Ndx => BookCategory::NonScripture,
        }
    }

    pub fn is_old_testament(&self) -> bool {
        self.category() == BookCategory::OldTestament
    }

    pub fn is_new_testament(&self) -> bool {
        self.category() == BookCategory::NewTestament
    }

    pub fn is_deuterocanon(&self) -> bool {
        self.category() == BookCategory::Deuterocanon
    }

    pub fn is_non_scripture(&self) -> bool {
        self.category() == BookCategory::NonScripture
    }
}

impl fmt::Display for BookCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Gen => "GEN",
                Exo => "EXO",
                Lev => "LEV",
                Num => "NUM",
                Deu => "DEU",
                Jos => "JOS",
                Jdg => "JDG",
                Rut => "RUT",
                Sa1 => "1SA",
                Sa2 => "2SA",
                Ki1 => "1KI",
                Ki2 => "2KI",
                Ch1 => "1CH",
                Ch2 => "2CH",
                Ezr => "EZR",
                Neh => "NEH",
                Est => "EST",
                Job => "JOB",
                Psa => "PSA",
                Pro => "PRO",
                Ecc => "ECC",
                Sng => "SNG",
                Isa => "ISA",
                Jer => "JER",
                Lam => "LAM",
                Ezk => "EZK",
                Dan => "DAN",
                Hos => "HOS",
                Jol => "JOL",
                Amo => "AMO",
                Oba => "OBA",
                Jon => "JON",
                Mic => "MIC",
                Nam => "NAM",
                Hab => "HAB",
                Zep => "ZEP",
                Hag => "HAG",
                Zec => "ZEC",
                Mal => "MAL",
                Mat => "MAT",
                Mrk => "MRK",
                Luk => "LUK",
                Jhn => "JHN",
                Act => "ACT",
                Rom => "ROM",
                Co1 => "1CO",
                Co2 => "2CO",
                Gal => "GAL",
                Eph => "EPH",
                Php => "PHP",
                Col => "COL",
                Th1 => "1TH",
                Th2 => "2TH",
                Ti1 => "1TI",
                Ti2 => "2TI",
                Tit => "TIT",
                Phm => "PHM",
                Heb => "HEB",
                Jas => "JAS",
                Pe1 => "1PE",
                Pe2 => "2PE",
                Jn1 => "1JN",
                Jn2 => "2JN",
                Jn3 => "3JN",
                Jud => "JUD",
                Rev => "REV",
                Tob => "TOB",
                Jdt => "JDT",
                Esg => "ESG",
                Wis => "WIS",
                Sir => "SIR",
                Bar => "BAR",
                Lje => "LJE",
                S3y => "S3Y",
                Sus => "SUS",
                Bel => "BEL",
                Ma1 => "1MA",
                Ma2 => "2MA",
                Ma3 => "3MA",
                Ma4 => "4MA",
                Es1 => "1ES",
                Es2 => "2ES",
                Man => "MAN",
                Ps2 => "PS2",
                Oda => "ODA",
                Pss => "PSS",
                Eza => "EZA",
                Ez5 => "5EZ",
                Ez6 => "6EZ",
                Dag => "DAG",
                Ps3 => "PS3",
                Ba2 => "2BA",
                Lba => "LBA",
                Jub => "JUB",
                Eno => "ENO",
                Mq1 => "1MQ",
                Mq2 => "2MQ",
                Mq3 => "3MQ",
                Rep => "REP",
                Ba4 => "4BA",
                Lao => "LAO",
                Xxa => "XXA",
                Xxb => "XXB",
                Xxc => "XXC",
                Xxd => "XXD",
                Xxe => "XXE",
                Xxf => "XXF",
                Xxg => "XXG",
                Frt => "FRT",
                Bak => "BAK",
                Oth => "OTH",
                Int => "INT",
                Cnc => "CNC",
                Glo => "GLO",
                Tdx => "TDX",
                Ndx => "NDX",
            }
        )
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct UnknownBookCodeError;

impl FromStr for BookCode {
    type Err = UnknownBookCodeError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_uppercase().as_str() {
            "GEN" => Ok(Gen),
            "EXO" => Ok(Exo),
            "LEV" => Ok(Lev),
            "NUM" => Ok(Num),
            "DEU" => Ok(Deu),
            "JOS" => Ok(Jos),
            "JDG" => Ok(Jdg),
            "RUT" => Ok(Rut),
            "1SA" => Ok(Sa1),
            "2SA" => Ok(Sa2),
            "1KI" => Ok(Ki1),
            "2KI" => Ok(Ki2),
            "1CH" => Ok(Ch1),
            "2CH" => Ok(Ch2),
            "EZR" => Ok(Ezr),
            "NEH" => Ok(Neh),
            "EST" => Ok(Est),
            "JOB" => Ok(Job),
            "PSA" => Ok(Psa),
            "PRO" => Ok(Pro),
            "ECC" => Ok(Ecc),
            "SNG" => Ok(Sng),
            "ISA" => Ok(Isa),
            "JER" => Ok(Jer),
            "LAM" => Ok(Lam),
            "EZK" => Ok(Ezk),
            "DAN" => Ok(Dan),
            "HOS" => Ok(Hos),
            "JOL" => Ok(Jol),
            "AMO" => Ok(Amo),
            "OBA" => Ok(Oba),
            "JON" => Ok(Jon),
            "MIC" => Ok(Mic),
            "NAM" => Ok(Nam),
            "HAB" => Ok(Hab),
            "ZEP" => Ok(Zep),
            "HAG" => Ok(Hag),
            "ZEC" => Ok(Zec),
            "MAL" => Ok(Mal),
            "MAT" => Ok(Mat),
            "MRK" => Ok(Mrk),
            "LUK" => Ok(Luk),
            "JHN" => Ok(Jhn),
            "ACT" => Ok(Act),
            "ROM" => Ok(Rom),
            "1CO" => Ok(Co1),
            "2CO" => Ok(Co2),
            "GAL" => Ok(Gal),
            "EPH" => Ok(Eph),
            "PHP" => Ok(Php),
            "COL" => Ok(Col),
            "1TH" => Ok(Th1),
            "2TH" => Ok(Th2),
            "1TI" => Ok(Ti1),
            "2TI" => Ok(Ti2),
            "TIT" => Ok(Tit),
            "PHM" => Ok(Phm),
            "HEB" => Ok(Heb),
            "JAS" => Ok(Jas),
            "1PE" => Ok(Pe1),
            "2PE" => Ok(Pe2),
            "1JN" => Ok(Jn1),
            "2JN" => Ok(Jn2),
            "3JN" => Ok(Jn3),
            "JUD" => Ok(Jud),
            "REV" => Ok(Rev),
            "TOB" => Ok(Tob),
            "JDT" => Ok(Jdt),
            "ESG" => Ok(Esg),
            "WIS" => Ok(Wis),
            "SIR" => Ok(Sir),
            "BAR" => Ok(Bar),
            "LJE" => Ok(Lje),
            "S3Y" => Ok(S3y),
            "SUS" => Ok(Sus),
            "BEL" => Ok(Bel),
            "1MA" => Ok(Ma1),
            "2MA" => Ok(Ma2),
            "3MA" => Ok(Ma3),
            "4MA" => Ok(Ma4),
            "1ES" => Ok(Es1),
            "2ES" => Ok(Es2),
            "MAN" => Ok(Man),
            "PS2" => Ok(Ps2),
            "ODA" => Ok(Oda),
            "PSS" => Ok(Pss),
            "EZA" => Ok(Eza),
            "5EZ" => Ok(Ez5),
            "6EZ" => Ok(Ez6),
            "DAG" => Ok(Dag),
            "PS3" => Ok(Ps3),
            "2BA" => Ok(Ba2),
            "LBA" => Ok(Lba),
            "JUB" => Ok(Jub),
            "ENO" => Ok(Eno),
            "1MQ" => Ok(Mq1),
            "2MQ" => Ok(Mq2),
            "3MQ" => Ok(Mq3),
            "REP" => Ok(Rep),
            "4BA" => Ok(Ba4),
            "LAO" => Ok(Lao),
            "XXA" => Ok(Xxa),
            "XXB" => Ok(Xxb),
            "XXC" => Ok(Xxc),
            "XXD" => Ok(Xxd),
            "XXE" => Ok(Xxe),
            "XXF" => Ok(Xxf),
            "XXG" => Ok(Xxg),
            "FRT" => Ok(Frt),
            "BAK" => Ok(Bak),
            "OTH" => Ok(Oth),
            "INT" => Ok(Int),
            "CNC" => Ok(Cnc),
            "GLO" => Ok(Glo),
            "TDX" => Ok(Tdx),
            "NDX" => Ok(Ndx),
            _ => Err(UnknownBookCodeError),
        }
    }
}
