[package]
name = "usfm_language_server"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
data_layer = { path = "../data_layer" }
regex = { workspace = true }
ropey = { workspace = true }
rusqlite = { workspace = true }
rusqlite_regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower-lsp-server = { workspace = true, features = ["proposed"] }
unic = { workspace = true }
