#!/usr/bin/env python3
"""Write the third-party notices for what the extension ships.

The VS Code extension carries two binaries, `usfm-language-server` and
`usfm`, and one JavaScript bundle, `out/main.js`. Each one contains code and
data under someone else's licence, and every one of those licences (MIT,
Apache-2.0, BSD, ISC, CC BY 4.0) asks that its notice travel with the copy.
This script gathers them into one text file:

- the Rust crates the two binaries link, for every target (`cargo tree
  --target all -e normal`, so a Windows or macOS build is covered too), each
  with the licence files its published package ships;
- the npm packages esbuild bundles into `out/main.js`: everything
  `package-lock.json` does not mark `dev`, read from `node_modules`, so run
  it after `npm ci`;
- the two things NOTICE.md lists that are compiled in rather than depended
  on: Paratext's stylesheet (CC BY 4.0) and the code adapted from oxc (MIT).

A package with no licence file of its own is an error, not a silent gap: the
file would then name a licence without carrying its text. `--check` does the
same collection and writes nothing, and `--no-npm` leaves the npm half out,
which is how `scripts/gate.sh` runs it (the gate installs no `node_modules`),
so a new crate without a licence file fails the gate the day it is added.

Usage:
    scripts/third_party_notices.py --output vscode/ThirdPartyNotices.txt
    scripts/third_party_notices.py --check --no-npm
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The packages whose dependencies ship. `usfm_cli` is the `usfm` binary.
BINARIES = ["usfm_language_server", "usfm_cli"]

# What a licence file is called, at the top of a package: LICENSE,
# LICENSE-MIT, LICENCE.txt, COPYING, UNLICENSE, NOTICE (Apache-2.0's own
# file, which section 4(d) says must travel too), and so on.
LICENSE_FILE = re.compile(r"^(licen[cs]e|copying|unlicense|notice)([-._].*)?$", re.I)

RULE = "=" * 79

HEADER = """\
Third-party notices for the USFM extension

The USFM extension, its `usfm-language-server` and `usfm` binaries and its
JavaScript bundle are MIT licensed, Copyright (c) 2025-2026 Michael Brown
(see LICENSE). They contain the third-party material below, which keeps its
own terms. This file is generated by scripts/third_party_notices.py.
"""

EMBEDDED = """\
Paratext's USFM stylesheet
--------------------------

The stylesheet compiled into both binaries is built from `usfm_sb.sty`
(version 3.0.11), the default stylesheet of Paratext by United Bible Societies
and SIL International, as distributed in the USFM/USX technical committee's
test suite, https://github.com/usfm-bible/tcdocs (`grammar/usfm_sb.sty`).
Copyright (c) 2022-2023 the members of the USFM/USX technical committee.
Licensed under the Creative Commons Attribution 4.0 International licence,
https://creativecommons.org/licenses/by/4.0/. It is used unmodified, with this
project's own additions appended to it.

oxc
---

The lexer's source cursor and the `Span` type are adapted from oxc,
https://github.com/oxc-project/oxc.

The MIT License (MIT)

Copyright (c) 2023-present VoidZero Inc. & Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


class Package:
    def __init__(self, ecosystem, name, version, license, directory, files):
        self.ecosystem = ecosystem
        self.name = name
        self.version = version
        self.license = license
        self.directory = directory
        self.files = files


def licence_files(directory, named=None):
    found = sorted(p for p in directory.iterdir() if p.is_file() and LICENSE_FILE.match(p.name))
    if named:
        path = directory / named
        if path.is_file() and path not in found:
            found.insert(0, path)
    return found


def rust_packages():
    metadata = json.loads(
        subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--locked"],
            cwd=ROOT, check=True, capture_output=True, text=True,
        ).stdout
    )
    by_id = {(p["name"], p["version"]): p for p in metadata["packages"]}

    tree = subprocess.run(
        ["cargo", "tree", "--locked", "--target", "all", "-e", "normal",
         "--prefix", "none", "--format", "{p}"]
        + [arg for name in BINARIES for arg in ("-p", name)],
        cwd=ROOT, check=True, capture_output=True, text=True,
    ).stdout

    packages = {}
    for line in tree.splitlines():
        parts = line.split()
        if len(parts) < 2:
            continue
        name, version = parts[0], parts[1].removeprefix("v")
        package = by_id.get((name, version))
        if package is None or package["source"] is None:
            continue  # a workspace crate: this project's own code
        directory = Path(package["manifest_path"]).parent
        files = licence_files(directory, package.get("license_file"))
        packages[(name, version)] = Package(
            "crate", name, version,
            package.get("license") or package.get("license_file") or "(not stated)",
            directory, files,
        )
    return sorted(packages.values(), key=lambda p: (p.name, p.version))


def npm_packages():
    lock = json.loads((ROOT / "package-lock.json").read_text())
    packages = []
    for key, entry in lock["packages"].items():
        if "node_modules/" not in key or entry.get("dev") or entry.get("devOptional"):
            continue
        if entry.get("link"):
            continue  # the extension's own workspace package
        directory = ROOT / key
        if not directory.is_dir():
            sys.exit(f"{key} is not installed: run `npm ci` first, or pass --no-npm")
        manifest = json.loads((directory / "package.json").read_text())
        name = manifest.get("name") or key.rsplit("node_modules/", 1)[1]
        packages.append(Package(
            "npm", name, manifest.get("version", entry.get("version", "?")),
            manifest.get("license") or entry.get("license") or "(not stated)",
            directory, licence_files(directory),
        ))
    # Nested copies of one package at one version are one entry.
    unique = {(p.name, p.version): p for p in packages}
    return sorted(unique.values(), key=lambda p: (p.name, p.version))


def render(packages):
    # Many packages ship word-for-word the same licence file (Apache-2.0's
    # text above all), so packages whose files read the same are listed
    # together over one copy of the text. The files differ wherever a
    # copyright line does, so nothing a notice names is merged away.
    groups = {}
    for package in packages:
        texts = tuple(
            (path.name, path.read_text(encoding="utf-8", errors="replace").strip())
            for path in package.files
        )
        groups.setdefault(tuple(t for _, t in texts), (texts, []))[1].append(package)

    out = [HEADER, RULE, "", EMBEDDED]
    for texts, members in sorted(groups.values(), key=lambda g: (g[1][0].name, g[1][0].version)):
        out += [RULE, ""]
        out += [f"{p.name} {p.version} ({p.ecosystem}), licence: {p.license}" for p in members]
        out += [""]
        for name, text in texts:
            out += [f"--- {name} ---", "", text, ""]
    return "\n".join(out).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--output", type=Path, help="write the notices here")
    action.add_argument("--check", action="store_true",
                        help="only check that every package ships a licence file")
    parser.add_argument("--no-npm", action="store_true",
                        help="leave out the npm packages (no node_modules needed)")
    args = parser.parse_args()

    packages = rust_packages()
    if not args.no_npm:
        packages += npm_packages()

    missing = [p for p in packages if not p.files]
    if missing:
        for p in missing:
            print(f"error: {p.ecosystem} {p.name} {p.version} ({p.license}) ships no "
                  f"licence file in {p.directory}", file=sys.stderr)
        sys.exit(1)

    if args.check:
        print(f"third-party notices: {len(packages)} packages, every one with a licence file")
        return
    args.output.write_text(render(packages), encoding="utf-8")
    print(f"wrote {args.output} ({len(packages)} packages)")


if __name__ == "__main__":
    main()
